name: Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Copy .env
      run: cp .env.example .env
    - name: Create SQLite database
      run: touch database/database.sqlite
    - name: Generate application key
      run: php artisan key:generate
    - name: Run migrations
      run: php artisan migrate
    - name: Run tests
      run: ./vendor/bin/pest
